### ISSUE TITLE
Where can I get the docs about Native Instruments MIDI Protocol?

### ISSUE THREAD

**Issue by moutend** [jcsteh/reaKontrol#12]
Hi, @jcsteh. This might be a question rather than an issue.

Is there an official documentation about Native Instruments MIDI protocol? I tried roughly googling, but I couldn't find that documentation.

I'm also interested in the steps to implement this plugin. How did you investigate the internal behavior of the KOMPLETE KONTROL software?

Anyway, my KKA61 works fine with the reaKontrol!

**Comment by jcsteh** [comment]
There is no public documentation. NI has documentation they can give you under NDA, but despite me signing the NDA, they still haven't sent it to me yet. That said, [the source code to the DrivenByMoss driver](https://github.com/git-moss/DrivenByMoss/tree/master/src/main/java/de/mossgrabers/controller/kontrol/midi/mkii) is open source and you can figure most of it out from there. The rest you can figure out by looking at MIDI messages received from the controller.

**Comment by moutend** [comment]
Thank you for quick reply. I got it. I hope NI becomes more open-source friendly.

**Comment by jcsteh** [comment]
Sad to say, I wouldn't hold your breath. They've been pretty unhelpful thus
far, despite claiming to care about REAPER as a supported DAW.

**Comment by sleiner** [comment]
I‘m currently trying to reverse-engineer another part of the protocol (recalling of user MIDI presets).
@jcsteh could you give me a hint on how to sniff the MIDI traffic between the Komplete Kontrol application and the NI Hardware service?

**Comment by jcsteh** [comment]
No idea. I've never monitored MIDI trafic from apps I didn't control. That hasn't been necessary for the work I've done on this. Note that it's possible it doesn't even use MIDI for some things.

**Comment by sleiner** [comment]
Thanks! I'll have to conduct some further research then 👍

**Comment by brummbrum** [comment]
The only way to sniff on a MIDI connection in Windows that I have heard of is via this (the SDK is linked on the website):
https://www.tobias-erichsen.de/software/virtualmidi.html

All other methods require you to route the traffic first via virtual MIDI ports (like loopMIDI, loopBE, MIDIyoke etc) which you cannot between NIHIA and KK (or NIHIA and Maschine). However, I doubt that KK actually uses MIDI to communicate with NIHIA. At the very least it will use other protocols in addition to that as it would be weird for NI developers to piggy back things like transmitting pictures over the clumsy MIDI protocol...
