### ISSUE TITLE
Auto instance switching does not work on A series keyboards

### ISSUE THREAD

**Issue by Flameborn** [jcsteh/reaKontrol#29]
Automatic instance switching does not work properly when switching tracks via a pc keyboard.

Steps to reproduce:

1. Add 2 tracks and a Komplete instance to each, preferably loading two different instruments.
2. Using the up and down arrow keys, switch to any of the tracks. If the product has NKS support, confirm with the Komplete knobs.
3. Switch to the next track.

The NKS knobs will still control the previous instrument, i.e. no instance switching happens.

The transport controls on the keyboard work as expected.

I am using the latest Reaper, v5.981, with the latest Reakontrol release build.

**Comment by jcsteh** [comment]
Curious. I believe others with A-series keyboards have tested this and not
experienced this issue.

If you open the FX parameters for a KK instance, is the first parameter
named, for example, NIKB00 (where the number changes depending on the
instance)?

**Comment by Flameborn** [comment]
This might be the issue. The first parameter is always 'NIKB00 (1)', no matter which track is selected.

I believe this is happening since the latest Komplete update.

**Comment by Flameborn** [comment]
Found the issue. If compatibility mode is set to 'In dedicated process per-plugin', the first parameter will remain NIKB00, regardless of the number of added instances.

Thank you very much for pointing me in the right direction.
