### ISSUE TITLE
Expression Pedal for M32

### ISSUE THREAD

**Issue by geej99** [jcsteh/reaKontrol#31]
Can reaKontrol do anything with the Expression Pedal to get it to work. Right now the M32 natively only recognizes the 0 and 127 - nothing in between.
And although it can trigger on or off for sustain, the pedal/M32 are wired backwards - pedal down is OFF and pedal up is ON. It woud be nice to have incremental values for sustain.

**Comment by jcsteh** [comment]
I'm afraid not. I think that's something only NI can fix.
