### ISSUE TITLE
node/electron warning

### ISSUE THREAD

**Issue by ageis** [jcsteh/reaKontrol#32]
Building @brummbrum's fork.
## Node/electron warning:

```
(node:17216) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some
point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```
## etc..

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
link /nologo /OPT:REF /dll /out:build\reaper_kontrol.dll /implib:build\reaper_kontrol.lib winmm.lib SetupAPI.lib /PDB:build\reaper_k
ontrol.dll.pdb /DEBUG build\main.obj build\niMidi.obj
scons: *** [build\reaper_kontrol.dll] Error 3221225781
scons: building terminated because of errors.
```

**Comment by jcsteh** [comment]
If you have an issue with a fork, please file the issue against that fork. I can't resolve issues with a fork here. Thanks.

For what it's worth, I don't think that node/electron warning is related to ReaKontrol. I don't know how you have things set up, but ReaKontrol doesn't use Node or Electron at all, so I'm wondering whether it's related to some IDE you're using (e.g. VS Code, Atom).

**Comment by ageis** [comment]
@jcsteh yeah I understand, the thing is @brummbrum's fork does not have an Issues page. So actually I mostly filed this to get their attention, and to bring that problem to their attention. Thanks.

**Comment by jcsteh** [comment]
I don't believe the build scripts have been changed much even in the fork,
so the Node/Electron stuff is very unlikely to be a problem in ReaKontrol.

**Comment by ageis** [comment]
I think it's probably an issue on my end with my build environment or PATH. I get the same error both with your master branch and the fork. How can I obtain a more verbose log?

```
C:\dev\reaKontrol2>scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
link /nologo /OPT:REF /dll /out:build\reaper_kontrol.dll /implib:build\reaper_kontrol.lib winmm.lib SetupAPI.lib /PDB:build\reaper_kontrol.dll.pdb /DEBUG build\main.obj build\niMidi.obj
link: extra operand '/dll'
Try 'link --help' for more information.
scons: *** [build\reaper_kontrol.dll] Error 1
scons: building terminated because of errors.

C:\dev\reaKontrol2>cd ..

C:\dev>cd reaKontrol

C:\dev\reaKontrol>scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
link /nologo /OPT:REF /dll /out:build\reaper_kontrol.dll /implib:build\reaper_kontrol.lib winmm.lib SetupAPI.lib /PDB:build\reaper_kontrol.dll.pdb /DEBUG build\main.obj build\niMidi.obj build\mcu.obj
link: extra operand '/dll'
Try 'link --help' for more information.
scons: *** [build\reaper_kontrol.dll] Error 1
scons: building terminated because of errors.```

**Comment by ageis** [comment]
I guess it's my `link.exe`?

**Comment by ageis** [comment]
lol I just tried a bunch of `link.exe`.. from Cygwin, Msys64, packaged w/ Git, Visual Studio 2017 build tools. I'm not sure what would be after VC, but before I go there, is there a recommended toolchain?

**Comment by jcsteh** [comment]
As documented in the readme in my repo, Visual Studio 2017 Community. 2019
will probably work with an up-to-date SCons; I'm not sure.

**Comment by brummbrum** [comment]
Compiles without any issue here - still using the original tool chain (SCons)

**Comment by brummbrum** [comment]
PS: "original" tool chain is in my case: SCons 3.0.5 running in Python 2.7 environment. Should also work in updated versions.
