### ISSUE TITLE
Everything but the keys work

### ISSUE THREAD

**Issue by EzePeruano** [jcsteh/reaKontrol#33]
Every button on the Komplete Kontrol a49 works fine even the quantize button gives an unknown signal to reaper, buy the keys don't do any thing neither the knobs. I'm using a vst from cakewalk. Its just the electric piano that comes with cakewalk, somehow reaper detected it, but still cant use the keys to play some notes. I can still press play and record though. Don't purge me please I'm new to this .   Hope you are okey at home and thanks for the developers for this dll. Honestly you guys saved my Christmas's gift. By the way the same thing is has happen when I tried the DrivenByMoss.

**Comment by jcsteh** [comment]
ReaKontrol isn't responsible for the keys in any way, only the DAW controls (transport, mixer, etc.). If the keys aren't working, you don't have your MIDI inputs set up correctly somewhere.
