### ISSUE TITLE
When I navagate track with 4d nob,all track names will be announced all the time by order.

### ISSUE THREAD

**Issue by vgjh2005** [jcsteh/reaKontrol#4]
Hi:
Thanks for good works. 
I am using NVDA2019.1.
Step to reproduce:
1. Create a new project.
2. Create some new tracks.
3. Press 4d nob to left and right to navagate the tracks.
All navagated tracks name  will be announced. In order to know what track is focused, I need to wait to previous tracks name announcement have been finished. Thanks again for good works.

**Comment by leonardder** [comment]
Strictly spoken, this is a problem with OSARA and not ReaKontrol specific. I intended to fix this with a PR against OSARA, but this only fixes it for Windows 10 FCU and newer and does not yet work for JAWS.

**Comment by jcsteh** [comment]
The OSARA UIA Notifications PR won't fix it for NVDA either because NVDA doesn't cancel speech for any UIA notifications as far as I know. However, I think it's reasonable for us to get this changed.

In any case, as noted, this is not a ReaKontrol bug. Closing.

**Comment by jcsteh** [comment]
> The OSARA UIA Notifications PR won't fix it for NVDA either because NVDA doesn't cancel speech for any UIA notifications as far as I know.

Oh. I just saw nvaccess/nvda#9466, so yes, we could now make this work for NVDA. :)

**Comment by vgjh2005** [comment]
Thanks
